---
title: "09-21 CBASS drc's"
author: "ross"
date: "3/13/2023"
output: html_document
---

```{r setup, include=FALSE}
options(rlib_downstream_check = FALSE)
knitr::opts_chunk$set(echo = TRUE)
```

```{r libs_fxns}
library(drc)
library(quantreg)
library(mcr)
library(broom)
library(lubridate)
library(tidyverse)

# Create custom ggplot theme
theme_custom <- function() {
  theme_bw(base_size = 10, base_family = "Arial") %+replace%
    theme(
      panel.grid.major = element_blank(), 
      panel.grid.minor = element_blank(), 
      panel.background = element_blank(),
      panel.border = element_rect(color = "black", fill = NA),
      legend.background = element_rect(fill = NA, colour = NA),
      axis.title = element_text(size = 7),
      axis.text = element_text(size = 5)
    )
}

# Function to pivot IPAM data to long form with column for AOI
ipam_convert <- function(data) {
  data %>% select_if(~ !any(is.na(.))) %>%
  pivot_longer(cols = starts_with("f") | starts_with("y")) %>%
  separate(name, into = c("var", "aoi"), sep = "(?<=[A-Za-z_])(?=[0-9])")
}
```

# Import data
```{r import_data}
# Import metadata: order in which racks PAMmed, and order of genets on racks
genetmd <- readxl::read_xlsx("data/reproducibility/genet_map.xlsx") %>%
  mutate(date = as_date(date), position = as.numeric(position))
pammd <- readxl::read_xlsx("data/reproducibility/pam_order.xlsx") %>%
  mutate(file_id = paste0(file_id, ".csv"),
         date = as_date(date), n_corals = as.numeric(n_corals))

# Import PAM data
# List PAM files from 2021-09-06 and 2021-09-08
pamfiles1 <- list.files(path = "data/reproducibility/PAM_data/20210906_2", pattern = "*.csv", full.names = T)
pamfiles2 <- list.files(path = "data/reproducibility/PAM_data/20210908_2", pattern = "*.csv", full.names = T)
pamfiles <- c(pamfiles2, pamfiles1)

# Import data from each file
pam1 <- pamfiles %>%
  map_dfr(read_delim, delim = ";", .id = "file_id") %>%
  janitor::clean_names() %>%
  mutate(file_id = basename(pamfiles[as.numeric(file_id)]),
         date = as_date(date, format = "%d.%m.%y"))

# For files that have multiple sat pulses -- keep the last one only
pam1 <- pam1 %>%
  group_by(file_id, date) %>%
  filter(no == max(no)) %>%
  ungroup()

# For each source file, convert to long form data with F, FM, and YII for each AOI
pam1 <- pam1 %>%
  nest(-file_id, -date) %>%
  mutate(data2 = map(data, ipam_convert)) %>%
  unnest(data2) %>%
  group_by(file_id, date) %>%
  select(file_id, date, time, aoi, var, value)

# Join PAM data with rack order information (which PAM file corresponds to which rack of corals)
pam <- full_join(pam1, pammd) %>%
  group_by(file_id, date) %>%
  mutate(position = case_when(max(aoi) > n_corals ~ ceiling(as.numeric(aoi)/2),
                              max(aoi) == n_corals ~ as.numeric(aoi)))

# Join PAM data with coral genet and temperature treatment information (which AOI corresponds to which coral)
pam <- genetmd %>%
  full_join(pam, by = c("date", "rack", "position"))

# how many fvfm meas per genet per temp?
pam %>%
  filter(var == "y_ii_") %>%
  count(genet, temp) %>%
  arrange(-n)
```

# Fit dose-response curves to estimate ED50s
```{r fit_drc}
# Get Fv/Fm data and tidy
df <- pam %>%
  mutate(max_temp = as.numeric(temp)) %>%
  pivot_wider(names_from = var, values_from = value) %>%
  mutate(fvfmraw = y_ii_, fvfm = y_ii_) %>%
  select(geno = genet, nursery, max_temp, f, fm, fvfmraw, fvfm)

# Define function to fit 3-parameter LL model to data and return NULL if fitting error
ll3 <- function(data) {
  drm(fvfm ~ max_temp, data = data, 
      fct = LL.3(names = c("hill", "max", "ED50")),
      upperl = c(50, 0.7, 40),
      lowerl = c(20, 0.3, 30))}
tryll3 <- possibly(ll3, otherwise = NULL)

# Fit model to each coral, get parameters, fitted values, and residuals
initmods <- df %>%
  nest(data = c(max_temp, f, fm, fvfmraw, fvfm)) %>%
  # Fit the model to each coral
  mutate(ll3 = map(data, tryll3)) %>%
  # Get model parameters and fitted values/residuals
  mutate(pars = map(ll3, tidy),
         pred = map2(ll3, data, ~augment(.x, drop_na(.y, fvfm))))

# Extract ed50 parameter values from model fits
ed50 <- initmods %>% 
  select(nursery, geno, pars) %>%
  unnest(pars) %>%
  filter(term == "ED50")

# Collect raw data, fitted values, and diagnostics
vals <- initmods %>%
  select(nursery, geno, pred) %>%
  unnest(pred) %>%
  full_join(ed50) %>%
  full_join(df) %>%
  rename(ed50 = estimate) %>%
  mutate(problem = "none")
```

```{r drc_diagnostics}
# # Identify problematic data points based on cook's distance and residuals
counts <- vals %>%
  group_by(nursery, geno) %>%
  summarise(n = sum(!is.na(fvfm)))
dff <- vals %>%
  left_join(counts) %>%
  group_by(nursery, geno) %>%
  mutate(cooksd.thresh = 4/n) %>%   # Calculate cook's distance threshold as 4/n
  mutate(max_to_remove = floor(n * 0.2)) %>%
  ungroup() %>%
  mutate(problem = case_when(.cooksd > cooksd.thresh & !max_temp %in% c(30, 38) ~ "high cook's distance", # don't allow 30 and 38 to be removed based on cooksd
                             TRUE ~ "none")) %>%
  group_by(nursery, geno, outlier = problem %in% c("high cook's distance", "high residual")) %>%
  mutate(n.outliers = n(),
         rank.out = order(.cooksd, decreasing = TRUE)) %>%
  ungroup() %>%
  mutate(fvfm = case_when(outlier & rank.out <= max_to_remove & !max_temp %in% c(30, 38) ~ NA_real_,
                          TRUE ~ fvfm))

# Refit models without problematic points
fmods <- dff %>%
  select(nursery, geno, max_temp, f, fm, fvfmraw, problem, fvfm) %>%
  nest(data = c(max_temp, f, fm, fvfmraw, fvfm, problem)) %>%
  # Fit the model to each coral
  mutate(ll3 = map(data, tryll3)) %>%
  # Get model parameters and fitted values/residuals
  mutate(pars = map(ll3, tidy),
         pred = map2(ll3, data, ~augment(.x, drop_na(.y, fvfm))))

# Extract ed50 parameter values from model fits
fed50 <- fmods %>%
  select(nursery, geno, pars) %>%
  unnest(pars) %>%
  filter(term == "ED50")

# Collect raw data, fitted values, and ed50 estimates
fvals <- fmods %>%
  select(nursery, geno, pred) %>%
  unnest(pred) %>%
  full_join(fed50) %>%
  full_join(select(dff, nursery, geno, max_temp, f, fm, fvfmraw, problem, fvfm)) %>%
  rename(ed50 = estimate)
```

# Plot dose response curves for each genotype
```{r plot, fig.width = 10, fig.height = 10}
# Plot fits
## Reorder genotypes by ED50 in decreasing order
fvals.ord <- fvals %>%
  mutate(geno = fct_reorder(factor(geno), ed50, .fun = mean, na.rm = TRUE, .desc = TRUE))
vals.ord <- vals %>%
  mutate(geno = factor(geno, levels = levels(fvals.ord$geno)))
ed50 <- ed50 %>% mutate(geno = factor(geno, levels = levels(fvals.ord$geno)))
fed50 <- fed50 %>% mutate(geno = factor(geno, levels = levels(fvals.ord$geno)))

ggplot(fvals.ord, aes(x = max_temp)) + 
    facet_wrap(~ geno) +
    geom_point(aes(y = fvfmraw, shape = is.na(fvfm)), size = 1) + 
    geom_line(data = drop_na(fvals.ord), aes(y = .fitted), lty = 1) + 
    geom_line(data = vals.ord, aes(y = .fitted), lty = 2) + 
    geom_vline(data = ed50, aes(xintercept = estimate), lwd = 0.25, lty = 2) +
    geom_vline(data = fed50, aes(xintercept = estimate), lwd = 0.25, lty = 1) +
    scale_shape_manual(values = c(1, 4)) +
    geom_text(data = fed50,
              aes(x = estimate, y = 0.05, label = round(estimate, 2)), 
              hjust = 1, nudge_x = -0.2, size = 2) +
    theme_classic() +
    theme(legend.position = "none")
```

```{r}
ed50 %>%
  select(nursery, geno, ed50 = estimate, std.error) %>%
  left_join(select(fed50, nursery, geno, ed50.f = estimate, std.error.f = std.error)) %>%
  write_csv("data/reproducibility/processed/ed50_202109.csv")
```

