---
title: "CBASS_temp_logs.Rmd"
author: "ross"
date: "8/20/2023"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### HOBO data

```{r}


#Obtaining HOBO Serial Numbers for CBASS Runs
hoboSerialsAll <- NULL
files <- list.files(path = "data/CBASS_HOBOs", pattern='2023', recursive = TRUE, full.names = TRUE)
for (i in files){
  dat <- suppressMessages(rio::import(i, sheet = "Details")) %>% 
    dplyr::select(c(3:4)) %>% 
    dplyr::filter(`...3` %in% c("Serial Number","Name","First Sample Time")) %>% 
    unique() %>% 
    pivot_wider(names_from = `...3`,
                values_from = `...4`)
  hoboSerialsAll <- suppressMessages(plyr::rbind.fill(hoboSerialsAll,dat))
}

hoboSerialsAll <- hoboSerialsAll %>% 
  separate("First Sample Time", into = c("dateCBASS",NA), sep = " ") %>% 
  mutate(dateCBASS = as.character(lubridate::ymd(dateCBASS))) %>% 
  unique()


# Read in HOBO data from all CBASS runs
source("Code/hoboDHWs.R")
runs <- list.dirs(path = "data/CBASS_HOBOs", recursive = FALSE, full.names = TRUE)
hobo <- NULL

for (day in runs) {
  name <- substr(day,nchar("data/CBASS_HOBOs/") + 1, nchar(day))
  hoboDay <- hoboDHWs(path = day, summary = FALSE, calc = FALSE) %>% 
    tidyr::separate(Group, c("Tank"), sep = " ") %>% 
    dplyr::mutate(dateCBASS = name)
  hobo <- plyr::rbind.fill(hobo, hoboDay)
}

hobo <- hobo %>%
  rename(Name = Tank) %>%
  left_join(hoboSerialsAll)

# Apply HOBO offsets
hobo_offsets <- read_csv("data/processed/hobo_offsets.csv") %>%
  mutate(hoboSerial = as.character(hoboSerial))

hobo <- hobo %>% as_tibble() %>%
  rename(hoboSerial = `Serial Number`) %>%
  left_join(hobo_offsets) %>%
  mutate(hoboTemp.adj = `Temperature °C` - offset,
         max_temp = factor(str_sub(Name, 1, 2))) %>%
  select(dateCBASS, max_temp, DateTime, hoboSerial, hoboTemp.adj)

hobo
hobotempsfig <- ggplot(hobo, aes(x = DateTime, y = hoboTemp.adj, group = max_temp, color = max_temp)) +
  geom_line(lwd = 0.5, alpha = 1) +
  facet_wrap(~ dateCBASS, scales = "free_x") +
  theme(legend.position = "none") +
  scale_y_continuous(limits = c(29.5, 38.5), breaks = seq(30, 38, 1)) +
  labs(x = "Time", y = "Temperature (°C)"); hobotempsfig

```




### Temp sensor log data
```{r}
# Read in CBASS temperature logs and filter for just December 4th run
cbasslogs <- list.files(path = "data/CBASS_logs", pattern = "LOG.TXT", recursive = TRUE, full.names = TRUE)

cbasstemps <- map_dfr(cbasslogs, read_csv) %>%
  # Remove internal header rows
  filter(PrintDate != "PrintDate") %>%
  # Format date and time
  mutate(date = as_date(Date, format = "%Y_%m_%d")) %>%
  unite(time, Th, Tm, Ts, sep = ":") %>%
  unite(dttm, date, time) %>%
  mutate(dttm = ymd_hms(dttm)) %>%
  # Filter to start of CBASS runs on DRTO cruise, June 20th
  filter(dttm >= as_datetime("2023-06-20 00:00:00")) %>%
  select(dttm, ShortUniqueID, T1SP, TempT1, T2SP, TempT2, T3SP, TempT3, T4SP, TempT4) %>%
  # Pivot to long format
  pivot_longer(starts_with("T"), names_to = "key", values_to = "temp") %>%
  # Remove rows where temp sensors gave error codes
  filter(temp > 0, temp < 50) %>%
  # Parse tanks, setpoints, and actual temps
  mutate(probe = str_extract(key, "T[0-9]"),
         key = case_when(grepl("SP", key) ~ str_sub(key, 3, 4),
                         TRUE ~ str_sub(key, 1, 4)),
         key = tolower(key)) %>%
  # Filter to only get one temperature reading per second by averaging
  group_by(dttm, ShortUniqueID, probe, key) %>%
  summarize(temp = mean(as.numeric(temp), na.rm = TRUE)) %>%
  ungroup() %>%
  # Create columns for set point and actual temperature
  pivot_wider(names_from = key, values_from = temp) %>%
  # Tidy column types
  mutate(probe = factor(probe)) %>%
  # Add maximum setpoint temperature as max_temp column
  group_by(ShortUniqueID, probe) %>%
  mutate(max_temp = factor(max(sp, na.rm = TRUE))) %>%
  ungroup()

# Filter to just the hours of 12:30 to 21:30
cbasstemps <- cbasstemps %>%
  filter(hour(dttm) >= 12 & hour(dttm) <= 23)


cbasstempsthin <- cbasstemps %>%
  group_by(max_temp) %>%
  slice(which(row_number() %% 3 == 1)) %>%
  ungroup()

cbasstempsthin

cbasstempsfig <- ggplot(cbasstempsthin, aes(x = dttm, y = temp, group = max_temp, color = max_temp)) +
  geom_line(lwd = 0.5, alpha = 1) +
  facet_wrap(~ date(dttm), scales = "free_x") +
  theme(legend.position = "none") +
  scale_y_continuous(limits = c(29.5, 38.5), breaks = seq(30, 38, 1)) +
  labs(x = "Time", y = "Temperature (°C)"); cbasstempsfig

ggsave(cbasstempsfig, filename = "output/cbass_temps.png", width = 60, height = 80, units = "mm")
  

```

