---
title: "Untitled"
author: "ross"
date: "9/3/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(drc)
library(quantreg)
library(mcr)
library(broom)
library(lubridate)
library(tidyverse)

# Create custom ggplot theme
theme_custom <- function() {
  theme_bw(base_size = 10, base_family = "Arial") %+replace%
    theme(
      panel.grid.major = element_blank(), 
      panel.grid.minor = element_blank(), 
      panel.background = element_blank(),
      panel.border = element_rect(color = "black", fill = NA),
      legend.background = element_rect(fill = NA, colour = NA),
      axis.title = element_text(size = 7),
      axis.text = element_text(size = 5)
    )
}

# Labeller for treatments
treatment_labeller <- function(variable, value){
  return(list(
  'Normal'="High light",
  'lowLight'="Low light")[value])
}


# Function to pivot IPAM data to long form with column for AOI
ipam_convert <- function(data) {
  data %>% select_if(~ !any(is.na(.))) %>%
  pivot_longer(cols = starts_with("f") | starts_with("y")) %>%
  separate(name, into = c("var", "aoi"), sep = "(?<=[A-Za-z_])(?=[0-9])")
}
```

```{r}
# Import metadata: order in which racks PAMmed, and order of genets on racks
genetmd <- read_csv("data/light/genetmd.csv") %>%
  janitor::clean_names() %>%
  drop_na(genet) %>%
  mutate(date = as_date(cbass_date, format = "%m/%d/%y"), 
         position = as.numeric(position_number))  %>%
  select(date, nursery, rack_color, position, genet, treatment, frag_notes)
pammd <- read_csv("data/light/ipammd.csv") %>%
  janitor::clean_names() %>%
  drop_na(cbass_run) %>%
  mutate(file_id = paste0(picture, ".csv"),
         date = as_date(date, format = "%m/%d/%y"),
         max_temp = tank)
```

# Import I-PAM data
```{r}
# Import PAM data
# List PAM files from 2021-09-06
pamfiles <- list.files(path = "data/light/ipam", pattern = "*.csv", full.names = T)

# Import data from each file
pam1 <- pamfiles %>%
  map_dfr(read_delim, delim = ";", .id = "file_id") %>%
  janitor::clean_names() %>%
  mutate(file_id = basename(pamfiles[as.numeric(file_id)]),
         date = as_date(date, format = "%d.%m.%y"))

# For files that have multiple sat pulses -- keep the last one only
pam1 <- pam1 %>%
  group_by(file_id, date) %>%
  filter(no == max(no)) %>%
  ungroup()

# For each source file, convert to long form data with F, FM, and YII for each AOI
pam1 <- pam1 %>%
  nest(-file_id, -date) %>%
  mutate(data2 = map(data, ipam_convert)) %>%
  unnest(data2) %>%
  group_by(file_id, date) %>%
  select(file_id, date, time, aoi, var, value)

# Join PAM data with rack order information (which PAM file corresponds to which rack of corals)
pam <- full_join(pam1, pammd) %>%
  group_by(file_id, date) %>%
  mutate(position = as.numeric(aoi))

# Join PAM data with coral genet and temperature treatment information (which AOI corresponds to which coral)
pam <- genetmd %>%
  filter(genet != 77) %>%     # genet 77 not used in low light so no comparison
  left_join(pam, by = c("date", "rack_color", "position"))
```

# Fit dose-response curves
```{r}
# Get Fv/Fm data and tidy
df <- pam %>%
  pivot_wider(names_from = var, values_from = value) %>%
  mutate(fvfmraw = y_ii_, fvfm = y_ii_,
         max_temp = as.numeric(max_temp)) %>%
  select(geno = genet, nursery, treatment, max_temp, f, fm, fvfmraw, fvfm)

# Replace significant outlier for geno129, normal light, 30°C, where Fv/Fm was < 0.4, while fitted curve suggests should be around 0.55. This significantly affects ED50 so changing this values to 0.55.
df[df$geno == 129 & df$treatment == "Normal" & df$max_temp == 30, "fvfm"] <- 0.5

# Define function to fit 3-parameter LL model to data and return NULL if fitting error
ll3 <- function(data) {
  drm(fvfm ~ max_temp, data = data, 
      fct = LL.3(names = c("hill", "max", "ED50")),
      upperl = c(50, 0.7, 40),
      lowerl = c(20, 0.3, 30))}
tryll3 <- possibly(ll3, otherwise = NULL)

# Fit model to each coral, get parameters, fitted values, and residuals
initmods <- df %>%
  nest(data = c(max_temp, f, fm, fvfmraw, fvfm)) %>%
  # Fit the model to each coral
  mutate(ll3 = map(data, tryll3)) %>%
  # Get model parameters and fitted values/residuals
  mutate(pars = map(ll3, tidy),
         pred = map2(ll3, data, ~augment(.x, drop_na(.y, fvfm))))

# Extract ed50 parameter values from model fits
ed50 <- initmods %>% 
  select(nursery, geno, treatment, pars) %>%
  unnest(pars) %>%
  filter(term == "ED50")

# Collect raw data, fitted values, and diagnostics
vals <- initmods %>%
  select(nursery, geno, treatment, pred) %>%
  unnest(pred) %>%
  full_join(ed50) %>%
  full_join(df) %>%
  rename(ed50 = estimate) %>%
  mutate(problem = "none")
```

```{r drc_diagnostics}

# #### diagnostics
# Extract hill parameter values from model fits
# hill <- initmods %>%
#   select(nursery, geno, pars) %>%
#   unnest(pars) %>%
#   filter(term == "hill")
# ggplot(hill) +
#   geom_histogram(aes(x = estimate))
# hill %>% arrange(estimate)
# 
# maxes <- initmods %>%
#   select(nursery, geno, pars) %>%
#   unnest(pars) %>%
#   filter(term == "max")
# ggplot(maxes) +
#   geom_histogram(aes(x = estimate))
# maxes %>% arrange(-estimate)

# # Identify problematic data points based on cook's distance and residuals
counts <- vals %>%
  group_by(treatment, geno) %>%
  summarise(n = sum(!is.na(fvfm)))
dff <- vals %>%
  left_join(counts) %>%
  group_by(treatment, geno) %>%
  mutate(cooksd.thresh = 4/n) %>%   # Calculate cook's distance threshold as 4/n
  mutate(max_to_remove = floor(n * 0.2)) %>%
  ungroup() %>%
  mutate(problem = case_when(.cooksd > cooksd.thresh ~ "high cook's distance",
                             TRUE ~ "none")) %>%
  group_by(treatment, geno, outlier = problem %in% c("high cook's distance", "high residual")) %>%
  mutate(n.outliers = n(),
         rank.out = order(.cooksd, decreasing = TRUE)) %>%
  ungroup() %>%
  mutate(fvfm = case_when(outlier & rank.out <= max_to_remove ~ .fitted,
                          TRUE ~ fvfm))

# Refit models without problematic points
fmods <- dff %>%
  select(treatment, geno, max_temp, f, fm, fvfmraw, problem, fvfm) %>%
  nest(data = c(max_temp, f, fm, fvfmraw, fvfm, problem)) %>%
  # Fit the model to each coral
  mutate(ll3 = map(data, tryll3)) %>%
  # Get model parameters and fitted values/residuals
  mutate(pars = map(ll3, tidy),
         pred = map2(ll3, data, ~augment(.x, drop_na(.y, fvfm))))

# Extract ed50 parameter values from model fits
fed50 <- fmods %>%
  select(treatment, geno, pars) %>%
  unnest(pars) %>%
  filter(term == "ED50")

# Collect raw data, fitted values, and ed50 estimates
fvals <- fmods %>%
  select(treatment, geno, pred) %>%
  unnest(pred) %>%
  full_join(fed50) %>%
  full_join(select(dff, treatment, geno, max_temp, f, fm, fvfmraw, problem, fvfm)) %>%
  rename(ed50 = estimate)
```


# Plot dose response curves for each genotype
```{r plot, fig.width = 10, fig.height = 10}
ggplot(vals, aes(x = max_temp, y = fvfm, color = treatment)) +
  geom_point() +
  geom_line(aes(y = .fitted)) +
  facet_wrap(~geno)

# Group genotypes by similar ed50s across treatments
myd <- dist(res2[, c("Normal", "lowLight")])
myc <- hclust(myd)
plot(myc, labels = res2$geno)
grp <- cutree(myc, k = 4)

res2 <- ed50 %>%
  select(geno, treatment, estimate) %>%
  pivot_wider(names_from = treatment, values_from = estimate)  %>%
  mutate(diff = lowLight - Normal,
         grp = recode_factor(grp, "3" = "a", "4" = "b", "2" = "c", "1" = "d"))#levels = c("3", "4", "2", "1")))

#Linear model fit
mod <- lm(lowLight ~ Normal, data = res2)
mod
# Estimate/fit intercept with slope = 1
## Also, weight higher Normal ed50 points higher, since we think the lowest normal ed50 points are bucking the trend...so basically, fit line with slope 1 more to those points we think it applies to
b1 <- 1
#a <- weighted.mean(res2$lowLight - b1 * res2$Normal, w = (res2$Normal-34)^2)
## Or, get the intercept for JUST the corals that seem to follow the line!
a <- res2 %>% 
  filter(Normal > 34.9) %>%
  summarise(mean = mean(lowLight - b1 * Normal))


# sds <- ed50 %>%
#   group_by(treatment) %>%
#   summarise(mean = mean(estimate), sd = sd(estimate))
# ggplot(sds, aes(x = treatment, y = mean)) +
#   geom_point() +
#   geom_errorbar(aes(ymin = mean - sd, ymax = mean + sd), width = 0.3) +
#   theme_custom()

panelA <- ggplot(res2, aes(x = Normal, y = lowLight)) +
  geom_smooth(span = 1, lwd = 0.5) +
  geom_point(aes(color = grp)) +
  #geom_label(aes(label = geno, color = grp)) +
  #geom_abline(slope = 1, intercept = 0, lty = 2) +
  geom_abline(intercept = a[[1]], slope = b1, lty = 2) +
  #geom_abline(intercept = a + 0.72, slope = b1, lty = 2) +
  #geom_abline(intercept = a - 0.72, slope = b1, lty = 2) +
  coord_fixed(ylim = c(35.6, 36.7)) +
  labs(x = "ED50 (°C) under high light", y = "ED50 (°C) under low light") +
  #annotate("errorbar", aes(x = 35, y = 36, xmin = 35.13521 - 0.278297, xmax = 35.13521 + 0.278297)) +
  theme_custom() +
  theme(legend.position = "none"); panelA


mod <- res2 %>% 
  pivot_longer(cols = c("Normal", "lowLight"), names_to = "treatment", values_to = "ed50") %>%
  lm(ed50 ~ treatment * grp, data = .)
anova(mod)
emm <- data.frame(emmeans::emmeans(mod, specs = c("treatment", "grp")))
emmeans::emmeans(mod, specs = c("treatment", "grp"), contr = "pairwise", by = "treatment")

panelB <- ed50 %>%
  left_join(res2) %>%
  mutate(treatment = factor(treatment, levels = c("Normal", "lowLight"))) %>%
  ggplot(aes(x = grp, y = estimate, color = grp)) +
  geom_point(alpha = 0.5) +
  geom_point(data = emm, aes(y = emmean), pch = 3, size = 1.5) +
  geom_errorbar(data = emm, aes(y = emmean, ymin = emmean - SE, ymax = emmean + SE),
                width = 0.5) +
  facet_wrap(~ treatment, labeller = treatment_labeller) +
  labs(x = "Group", y = "ED50 (°C)") +
  theme_custom() +
  theme(legend.position = "none"); panelB


fig3 <- cowplot::plot_grid(panelA, panelB, ncol = 2); fig3
  
ggsave(fig3, filename = "output/fig3.png", width = 89, height = 52.5, units = "mm")

# Do some pairwise comparisons fall outside the test-rest probability range?

```


```{r}
# so all are within the 90% test-retest difference of 0.72 degrees, based on reproducibility experiment, so this all is within what we might expect from test-retest variability. But, the lowest four ed50s at normal light all did better than expected at low light. what are the chances that this would happen randomly? some kind of a permutation test?
# model the normal ed50 vs. residual of lowLight ed50?
# can we statistically model what the lowLight ed50s should be based on the normal ed50s and the known test-retest variability (like 1000 permutations)? then see that chances that actual lowLight ed50s could have been observed in this scenario?
# like the residuals are not random with respect to the Normal ed50...

res2 <- res2 %>%
  mutate(fitted = Normal + a,
         resid = lowLight - fitted)
ggplot(res2, aes(x = Normal, y = resid)) + geom_point() +
  geom_smooth(span = 0.75)

mod <- lm(resid ~ Normal, data = res2)
anova(mod)
plot(mod)
```


# Repeatability of pairwise ranks
```{r}
# Get all pairwise differences in adjusted ED50 between high confidence genos in 2020 and 2021
genos <- res2$geno
diffsN <- outer(res2$Normal, res2$Normal, `-`)
dimnames(diffsN) <- list(geno1 = genos, geno2 = genos)
diffsL <- outer(res2$lowLight, res2$lowLight, `-`)
dimnames(diffsL) <- list(geno1 = genos, geno2 = genos)

diffsN <- reshape2::melt(diffsN, value.name = "diff")
diffsL <- reshape2::melt(diffsL, value.name = "diff")
alldiffs <- as_tibble(full_join(diffsN, diffsL, by = c("geno1", "geno2"), suffix = c(".N", ".L")))

# Plot pairwise ED50 differences in 2021 as a function of how much HIGHER one genet's 2020 ED50 was
alldiffs %>% 
  filter(diff.N > 0) %>%       # Get all 2020 comparisons where genet 1 HIGHER than genet 2
  ggplot(aes(x = diff.N, y = diff.L)) +
  geom_point(alpha = 0.5) +
  geom_smooth(method = "lm", se = FALSE)

alldiffs %>% arrange(-diff.N)

diffs2 <- alldiffs %>% 
  filter(diff.N > 0) %>%
  mutate(higher21 = diff.L > 0)
ggplot(diffs2, aes(x = diff.20, y = higher21)) + geom_jitter()
mod <- glm(higher21 ~ diff.20, data = diffs2, family = "binomial")
anova(mod)

# Get probability that rank order is same given difference in 2020 ED50s
emm <- emmeans::emmeans(mod, specs = "diff.20", at = list(diff.20 = seq(0,1.5,0.01)), type = "response")

fig2 <- ggplot(data.frame(emm), aes(x = diff.20, y = prob)) +
  geom_line() +
  geom_ribbon(aes(ymin = asymp.LCL, ymax = asymp.UCL), alpha = 0.2) +
  labs(x = "Pairwise difference in ED50 (°C) in Test 1 (2020)",
       y = "Probability of same rank order in Test 2 (2021)") +
  scale_x_continuous(expand = c(0, 0)) +
  theme_custom() +
  coord_cartesian(ylim = c(0.5, 1), expand = c(0, 0)); fig2

ggsave(fig2, filename = "output/fig2.png", width = 89, height = 89, units = "mm")
```