---
title: "Reproducibility test"
author: "ross"
date: "8/25/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r libs_fxns}
options(rlib_downstream_check = FALSE)
library(drc)
library(mcr)
library(broom)
library(lubridate)
library(tidyverse)

# Create custom ggplot theme
theme_custom <- function() {
  theme_bw(base_size = 10, base_family = "Arial") %+replace%
    theme(
      panel.grid.major = element_blank(), 
      panel.grid.minor = element_blank(), 
      panel.background = element_blank(),
      panel.border = element_rect(color = "black", fill = NA),
      legend.background = element_rect(fill = NA, colour = NA)
    )
}

# Function to pivot IPAM data to long form with column for AOI
ipam_convert <- function(data) {
  data %>% select_if(~ !any(is.na(.))) %>%
  pivot_longer(cols = starts_with("f") | starts_with("y")) %>%
  separate(name, into = c("var", "aoi"), sep = "(?<=[A-Za-z_])(?=[0-9])")
}

```

# Import data
```{r import_data}
# Import metadata: order in which racks PAMmed, and order of genets on racks
genetmd <- readxl::read_xlsx("data/reproducibility/genet_map.xlsx") %>%
  mutate(date = as_date(date), position = as.numeric(position))
pammd <- readxl::read_xlsx("data/reproducibility/pam_order.xlsx") %>%
  mutate(file_id = paste0(file_id, ".csv"),
         date = as_date(date), n_corals = as.numeric(n_corals))

# Import PAM data
# List PAM files from 2021-09-06
pamfiles1 <- list.files(path = "data/reproducibility/PAM_data/20210906_old", pattern = "*.csv", full.names = T)
pamfiles2 <- list.files(path = "data/reproducibility/PAM_data/20210908", pattern = "*.csv", full.names = T)
pamfiles <- c(pamfiles2, pamfiles1)

# Import data from each file
pam1 <- pamfiles %>%
  map_dfr(read_delim, delim = ";", .id = "file_id") %>%
  janitor::clean_names() %>%
  mutate(file_id = basename(pamfiles[as.numeric(file_id)]),
         date = as_date(date, format = "%d.%m.%y"))

# For files that have multiple sat pulses -- keep the last one only
pam1 <- pam1 %>%
  group_by(file_id, date) %>%
  filter(no == max(no)) %>%
  ungroup()

# For each source file, convert to long form data with F, FM, and YII for each AOI
pam1 <- pam1 %>%
  nest(-file_id, -date) %>%
  mutate(data2 = map(data, ipam_convert)) %>%
  unnest(data2) %>%
  group_by(file_id, date) %>%
  select(file_id, date, time, aoi, var, value)

# Join PAM data with rack order information (which PAM file corresponds to which rack of corals)
pam <- full_join(pam1, pammd) %>%
  group_by(file_id, date) %>%
  mutate(position = case_when(max(aoi) > n_corals ~ ceiling(as.numeric(aoi)/2),
                              max(aoi) == n_corals ~ as.numeric(aoi)))

# Join PAM data with coral genet and temperature treatment information (which AOI corresponds to which coral)
pam <- genetmd %>%
  full_join(pam, by = c("date", "rack", "position"))
```

# Fit dose-response curves to estimate ED50s
```{r fit_drc}
# Get Fv/Fm data and tidy
df <- pam %>%
  mutate(max_temp = as.numeric(temp)) %>%
  pivot_wider(names_from = var, values_from = value) %>%
  mutate(fvfmraw = y_ii_, fvfm = y_ii_) %>%
  select(geno = genet, nursery, max_temp, f, fm, fvfmraw, fvfm)

# Define function to fit 3-parameter LL model to data and return NULL if fitting error
ll3 <- function(data) {
  drm(fvfm ~ max_temp, data = data, 
      fct = LL.3(names = c("hill", "max", "ED50")),
      upperl = c(50, 1, 40),
      lowerl = c(20, 0, 30))}
tryll3 <- possibly(ll3, otherwise = NULL)

# Fit model to each coral, get parameters, fitted values, and residuals
initmods <- df %>%
  nest(data = c(max_temp, f, fm, fvfmraw, fvfm)) %>%
  # Fit the model to each coral
  mutate(ll3 = map(data, tryll3)) %>%
  # Get model parameters and fitted values/residuals
  mutate(pars = map(ll3, tidy),
         pred = map2(ll3, data, ~augment(.x, drop_na(.y, fvfm))))

# Extract ed50 parameter values from model fits
ed50 <- initmods %>% 
  select(nursery, geno, pars) %>%
  unnest(pars) %>%
  filter(term == "ED50")

# Collect raw data, fitted values, and diagnostics
vals <- initmods %>%
  select(nursery, geno, pred) %>%
  unnest(pred) %>%
  full_join(ed50) %>%
  full_join(df) %>%
  rename(ed50 = estimate) %>%
  mutate(problem = "none")
```

```{r drc_diagnostics}

# #### diagnostics
# # Extract hill parameter values from model fits
# hill <- initmods %>% 
#   select(nursery, geno, pars) %>%
#   unnest(pars) %>%
#   filter(term == "hill")
# ggplot(hill) +
#   geom_histogram(aes(x = estimate))
# hill %>% arrange(estimate)
# 
# maxes <- initmods %>% 
#   select(nursery, geno, pars) %>%
#   unnest(pars) %>%
#   filter(term == "max")
# ggplot(maxes) +
#   geom_histogram(aes(x = estimate))
# maxes %>% arrange(-estimate)

# # Identify problematic data points based on cook's distance and residuals
# counts <- vals %>%
#   group_by(nursery, geno) %>%
#   summarise(n = sum(!is.na(fvfm)))
# dff <- vals %>%
#   left_join(counts) %>%
#   group_by(nursery, geno) %>%
#   mutate(resid.thresh = 2*sd(.resid, na.rm = T)) %>%  # Calculate residual threshold as 2 standard deviations
#   mutate(cooksd.thresh = 4/n) %>%   # Calculate cook's distance threshold as 4/n
#   mutate(max_to_remove = floor(n * 0.2)) %>%
#   ungroup() %>%
#   mutate(problem = case_when(.cooksd > cooksd.thresh & .resid > 0 ~ "high cook's distance",
#                              .resid > resid.thresh ~ "high residual",
#                              TRUE ~ "none")) %>%
#   group_by(nursery, geno, outlier = problem %in% c("high cook's distance", "high residual")) %>%
#   mutate(n.outliers = n(),
#          rank.out = order(.cooksd, decreasing = TRUE)) %>%
#   ungroup() %>%
#   mutate(fvfm = case_when(outlier & rank.out <= max_to_remove ~ NA_real_,
#                           TRUE ~ fvfm))
# 
# 
# # Refit models without problematic points
# fmods <- dff %>%
#   select(nursery, geno, max_temp, f, fm, fvfmraw, problem, fvfm) %>%
#   nest(data = c(max_temp, f, fm, fvfmraw, fvfm, problem)) %>%
#   # Fit the model to each coral
#   mutate(ll3 = map(data, tryll3)) %>%
#   # Get model parameters and fitted values/residuals
#   mutate(pars = map(ll3, tidy),
#          pred = map2(ll3, data, ~augment(.x, drop_na(.y, fvfm))))
# 
# # Extract ed50 parameter values from model fits
# fed50 <- fmods %>%
#   select(nursery, geno, pars) %>%
#   unnest(pars) %>%
#   filter(term == "ED50")
# 
# # Collect raw data, fitted values, and ed50 estimates
# fvals <- fmods %>%
#   select(nursery, geno, pred) %>%
#   unnest(pred) %>%
#   full_join(fed50) %>%
#   full_join(select(dff, nursery, geno, max_temp, f, fm, fvfmraw, problem, fvfm)) %>%
#   rename(ed50 = estimate)
```

# Plot dose response curves for each genotype
```{r plot, fig.width = 10, fig.height = 10}
# Define function to plot raw data, fitted values, and ed50 for each genotype
plotfits <- function(data) {
  ggplot(data = data, aes(x = max_temp)) + 
    geom_point(pch = 4, size = 1.25,
               aes(y = fvfmraw, color = factor(problem, levels = c("none", "no  signal",
                                              "abnormally high",  
                                              "abnormally high w/ low Ft",  
                                              "high residual", "high cook's distance")))) + 
    geom_point(aes(y = fvfm), pch = 1, size = 2) + 
    geom_line(data = drop_na(data, .fitted), 
              aes(y = .fitted)) + 
    geom_vline(data = distinct(data, nursery, geno, ed50),
               aes(xintercept = ed50), 
               lwd = 0.2, lty = 2) +
    geom_text(data = distinct(data, nursery, geno, ed50),
              aes(x = ed50, y = 0.05, label = round(ed50, 2)), 
              hjust = 1, nudge_x = -0.2, size = 3) +
    facet_wrap(~ nursery + geno, drop = TRUE) +
    scale_color_manual(name = "problem", drop = FALSE,
                       values = c("black", "yellow", "red", "orange", "blue", "turquoise"))
}

# Plot fits
plotfits(data = vals)
```

# Compare ED50s measured in 2021 to ED50s measured in 2020
```{r}
# Import data from 2020
ed50_2020 <- read_csv("~/Projects/CBASS_FL_Acer/data/processed/ed50_values.csv") %>%
  mutate(nursery = case_when(nursery == "mote" ~ "mml", TRUE ~ nursery),
         ed50_2020 = ed50, 
         std.error_2020 = std.error) %>%
  select(nursery, geno, ed50_2020, std.error_2020)

# In 2020, some genotypes were run multiple times from the same nursery, indicated by (A), (B), (C), etc.
# Group these, and get the average ED50 for 2020 for each genotype from each nursery
ed50_2020 <- ed50_2020 %>%
  separate(geno, into = c("geno", "replicate"), sep = "\\(") %>%
  group_by(geno, nursery) %>%
  summarise(ed50_2020 = weighted.mean(ed50_2020, 1/std.error_2020^2), std.error_2020 = mean(std.error_2020))

# Tidy 2021 data and join with 2020
ed50_2021 <- ed50 %>%
  mutate(ed50_2021 = estimate,
         std.error_2021 = std.error,
         nursery = tolower(nursery)) %>%
  select(nursery, geno, ed50_2021, std.error_2021)
alldf <- left_join(ed50_2021, ed50_2020, by = c("nursery", "geno"))

# Plot raw ED50 values from 2021 vs. 2020
ggplot(alldf, aes(x = ed50_2020, y = ed50_2021)) +
  geom_point(aes(color = nursery, shape = nursery)) +
  geom_errorbar(aes(xmin = ed50_2020 - std.error_2020, xmax = ed50_2020 + std.error_2020), lwd = 0.1) +
  geom_errorbar(aes(ymin = ed50_2021 - std.error_2021, ymax = ed50_2021 + std.error_2021), lwd = 0.1) +
  geom_text(aes(label = geno), size = 5) +
  geom_smooth(aes(color = nursery, shape = nursery), method = "lm", se = FALSE) +
  labs(x = "ED50 - 2020", y = "ED50 - 2021") +
  coord_fixed(ratio = 1, xlim = c(34.5, 37.0), ylim = c(34.5, 37.0)) +
  ggpubr::stat_cor(method = "pearson", label.y = 36.8, label.x = 34.5, size = 3)
  #ggpubr::stat_cor(method = "spearman", label.y = 36.8, label.x = 34.5, size = 3)

# Linear model for raw ED50 values
mod <- lm(ed50_2021 ~ ed50_2020 + nursery, data = alldf)
anova(mod)
```

# Adjust ED50 values for nursery:year effects
```{r}
# Pivot to long form to model nursery:year differences and then subtract residuals
# Removes differences due to nursery and year to focus on genotype differences only
long <- alldf %>% drop_na() %>%
  select(nursery, geno, ed50_2021, ed50_2020) %>%
  pivot_longer(cols = c(ed50_2021, ed50_2020), names_to = "year", values_to = "ed50") 
mod <- lm(ed50 ~ nursery:year, data = long)
res <- augment(mod, long) %>%
  mutate(ed50_adj = mean(long$ed50) + .resid)

# Confirm that all nursery:year groups now have same mean value
res %>%
  group_by(nursery, year) %>%
  summarise(meanvaladj = mean(ed50_adj))

# Pivot to wide form to model 2021 vs. 2020
res2 <- res %>%
  select(nursery, geno, year, ed50_adj) %>%
  pivot_wider(names_from = year, values_from = ed50_adj)

# Model adjusted ED50ʻs from 2021 vs. 2020
## Linear model
mod.lm <- lm(ed50_2021 ~ ed50_2020, data = res2)
anova(mod.lm)
summary(mod.lm)
## Passing-Bablok, Deming, and quantile regressions
paba.reg <- mcreg(res2$ed50_2020, res2$ed50_2021, method.reg = "PaBa")
dem.reg <- mcreg(res2$ed50_2020, res2$ed50_2021, method.reg = "Deming")
mod.rq <- rq(ed50_2021 ~ ed50_2020, data = res2)

# Plot with different regression lines
res2 %>%
  ggplot(aes(x = ed50_2020, y = ed50_2021)) +
  geom_point() + #aes(color = abs(ed50_2020-ed50_2021) < 0.5)) +
  #geom_abline(aes(slope = coef(mod.lm)[2], intercept = coef(mod.lm)[1])) +
  geom_abline(aes(slope = coef(mod.rq)[2], intercept = coef(mod.rq)[1])) +
  geom_abline(aes(slope = paba.reg@para[2], intercept = paba.reg@para[1]), color = "blue") +
  #geom_abline(aes(slope = dem.reg@para[2], intercept = dem.reg@para[1]), color = "red") +
  geom_abline(aes(slope = 1, intercept = 0), lty = 2) +
  ggpubr::stat_cor(method = "spearman", label.y = 36.8, label.x = 34.85, size = 3) +
  theme_custom() +
  theme(legend.position = "none")

res2 %>%
  count(within0.5 = abs(ed50_2020-ed50_2021) < 0.5) %>%
  mutate(perc = n / nrow(res2))

#
cor.test(res2$ed50_2020, res2$ed50_2021, method = "spearman")

res2 <- res2 %>%
  mutate(top_2020 = ed50_2020 > quantile(res2$ed50_2020, 0.5),
         top_2021 = ed50_2021 > quantile(res2$ed50_2021, 0.5))

res2 %>%
  count(top_2020, top_2021)

ggplot(res2, aes(x = ed50_2020, y = ed50_2021, color = top_2020, shape = top_2021)) +
  geom_point()


res2 %>%
  sample_n(2) %>%
  if(range(ed50_2020) >= 1) {
    
  }


calc <- function(z) {
  res3 <- vector()
  for (i in 1:nrow(res2)) {
    x <- res2[i, ]
    for (j in 1:nrow(res2)) {
      y <- res2[j, ]
      if (abs(x$ed50_2020 - y$ed50_2020) >= z) {
        rank20 <- x$ed50_2020 > y$ed50_2020
        rank21 <- x$ed50_2021 > y$ed50_2021
        res3 <- c(res3, rank20 == rank21)
      }
    }
  }
  res4 <- table(res3)
  return(res4["TRUE"]/sum(res4))
}
calc(0)
calc(0.25)
calc(0.5)
calc(1)
calc(1.2)
calc(1.3)
calc(1.4)
calc(1.5)


genets <- res2$geno
combos <- apply(combn(genets,2),2,paste,collapse='_')
pairs <- tibble(pair = combos) %>%
  separate(pair, into = c("genet1", "genet2"), sep = "_")

long

ed50_2020 %>%
  select(geno, ed50_2020) %>%
  dist()

dist(ed50_2020$ed50_2020)

left_join(pairs, ed50_2020)

combos <- combn(genets, 2, simplify = FALSE)
tibble(grp = unlist(combos))






x = c(1,2,3,4,5)    
apply(combn(x,2),2,paste,collapse='_')




# Get all pairwise differences between genos in 2020 and 2021
genos <- alldf$geno
diffs2020 <- outer(alldf$ed50_2020, alldf$ed50_2020, `-`)
dimnames(diffs2020) <- list(geno1 = genos, geno2 = genos)
diffs2021 <- outer(alldf$ed50_2021, alldf$ed50_2021, `-`)
dimnames(diffs2021) <- list(geno1 = genos, geno2 = genos)

diffs2021 <- reshape2::melt(diffs2021, value.name = "diff")
diffs2020 <- reshape2::melt(diffs2020, value.name = "diff")
alldiffs <- as_tibble(full_join(diffs2020, diffs2021, by = c("geno1", "geno2"), suffix = c(".20", ".21")))

# Plot pairwise ED50 differences in 2021 as a function of how much HIGHER one genet's 2020 ED50 was
alldiffs %>% 
  filter(diff.20 > 0) %>%       # Get all 2020 comparisons where genet 1 HIGHER than genet 2
  ggplot(aes(x = diff.20, y = diff.21)) +
  geom_point(alpha = 0.5) +
  geom_smooth(method = "lm", se = FALSE)

diffs2 <- alldiffs %>% 
  filter(diff.20 > 0) %>%
  mutate(higher21 = diff.21 > 0)
mod <- glm(higher21 ~ diff.20, data = diffs2, family = "binomial")
anova(mod)

# Get probability that rank order is same given difference in 2020 ED50s
pred <- tibble(diff.20 = seq(0, 2, 0.01))
emm <- emmeans::emmeans(mod, specs = "diff.20", at = list(diff.20 = seq(0,2,0.01)), type = "response")
data.frame(emm) %>%
  ggplot(aes(x = diff.20, y = prob)) +
  geom_line() +
  geom_ribbon(aes(ymin = asymp.LCL, ymax = asymp.UCL), alpha = 0.2) +
  labs(x = "Difference in ED50 measured in 2020",
       y = "Probability rank order holds in 2021")

# What about groups of n=5 genotypes?

```

```{r}
# Going back to .pim files and putting 2 AOIs per coral
# 9/6/21: 
#   pim file 1 is wrong corals / image saved incorrectly -- cannot get new data
#   pim file 2 only contains top 3 out of 5 corals from the rack in the image
#   pim file 3 is wrong corals
#   pim file 36 is the SAME as 35 -- must have been saved incorrectly...

```

